language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - clang-3.6
compiler:
  - clang-3.6
script:
  - mkdir build
  - cd build
  - cmake .. && make  
  - ./Tests
